[window]
padding.x = 5
padding.y = 5
opacity = 0.95
dynamic_title = true

[font.normal]
family = "Iosevka Term"
size = 16

[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black   = "#1F1F28"
red     = "#E46876"
green   = "#98BB6C"
yellow  = "#DCD478"
blue    = "#7FB4CA"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#DCD7BA"

[colors.bright]
black   = "#2D4F67"
red     = "#E46876"
green   = "#98BB6C"
yellow  = "#DCD478"
blue    = "#7FB4CA"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#DCD7BA"

[shell]
program = "wsl.exe"
args = ["-d", "Archlinux", "--exec", "zellij"]
