# Prefijo: Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Quitar la binding por defecto de 'd' que hace detach
unbind-key d

# Divisiones rápidas con prefix (Ctrl+a h / Ctrl+a d)
bind h split-window -h     
bind v split-window -v    

# Navegación entre paneles estilo Neovim (prefix NOT required)
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U

# Redimensionar -- opcional
bind -n C-M-Left resize-pane -L 5
bind -n C-M-Right resize-pane -R 5
bind -n C-M-Up resize-pane -U 5
bind -n C-M-Down resize-pane -D 5

# Minimalista
set -g mouse off
set -g status-bg colour234
set -g status-fg colour136
set -g status-left ""
set -g status-right "%Y-%m-%d %H:%M"
setw -g mode-keys vi

# Cuando abras un nuevo panel o ventana, que se abra en el mismo directorio
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
